name: test_cov
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 1.0.3
homepage: https://github.com/vitusortner/test_cov
authors:
  - Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
  - Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.12.0 <=3.3.8'

executables:
  test_cov:

dependencies:
  coverage: ^1.0.1
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.5
